name: Sync v2rayN Releases

on:
  schedule:
    - cron: "0 1 * * *"  # Daily at 01:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Fetch latest release metadata
        id: get-release
        run: |
          RESPONSE=$(curl -s "https://api.github.com/repos/2dust/v2rayN/releases/latest")
          TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "$RESPONSE" > release.json

      - name: Download assets
        run: |
          jq -r '.assets[].browser_download_url' release.json | xargs -n1 wget -q

      - name: Publish to fork
        run: |
          gh release create "${{ steps.get-release.outputs.tag_name }}" \
            --repo Aktesuixin/v2rayN \
            --title "${{ steps.get-release.outputs.tag_name }}" \
            --notes "Automatically synced from 2dust/v2rayN" \
            ./*.{exe,zip,7z,deb}  # Adjust extensions as needed
