name: Sync All Release Assets

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        shell: bash
        run: |
          mkdir -p ./assets
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Get Release Info
        id: release
        run: |
          latest=$(curl -s "https://api.github.com/repos/2dust/v2rayN/releases/latest")
          tag=$(jq -r '.tag_name' <<< "$latest")
          assets=$(jq -r '.assets[] | .browser_download_url' <<< "$latest" | wc -l)
          
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          echo "ASSET_COUNT=$assets" >> $GITHUB_OUTPUT
          echo "$latest" > release.json

      - name: Download All Assets
        run: |
          jq -r '.assets[].browser_download_url' release.json \
            | xargs -P 4 -I {} wget -q -P ./assets {}

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # 动态生成上传参数
          files=$(cd ./assets && ls | xargs -I {} echo "{}" | sed "s/^/'.\/assets\/&'/")
          
          gh release create ${{ steps.release.outputs.TAG }} \
            --title "${{ steps.release.outputs.TAG }}" \
            --notes "Synced from 2dust/v2rayN (${{ steps.release.outputs.ASSET_COUNT }} assets)" \
            $files

      - name: Cleanup
        if: always()
        run: rm -rf ./assets release.json
