name: Sync Source Code

on:
  workflow_dispatch:
    inputs:
      source_commit:
        description: 'Upstream commit SHA'
        required: false
  repository_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Branch Exists
        id: verify-branch
        run: |
          # 检查默认分支是否存在
          if ! git ls-remote --exit-code --heads origin ${{ github.ref_name }}; then
            echo "BRANCH_EXISTS=false" >> $GITHUB_OUTPUT
            echo "Using fallback branch: master"
          else
            echo "BRANCH_EXISTS=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON('["main", "master"]')[fromJSON(steps.verify-branch.outputs.BRANCH_EXISTS) && 0 || 1] }}
          path: fork-repo

      - name: Checkout Upstream
        uses: actions/checkout@v4
        with:
          repository: 2dust/v2rayN
          path: upstream
          fetch-depth: 0

      - name: Sync Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd upstream
          git remote set-url fork https://x-access-token:${GH_TOKEN}@github.com/Aktesuixin/v2rayN.git
          
          # 推送到动态分支
          git push fork HEAD:${{ github.ref_name || 'master' }} --force
          git push fork --tags --force
