name: Sync Releases Automatically

on:
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间 1:00 AM 自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Login to GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Download Latest Release from Source
        run: |
          gh release download --repo 2dust/v2rayN --pattern "*"

      - name: Get Release Tag
        id: get-tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/2dust/v2rayN/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Upload Release to Fork
        run: |
          gh release create "${{ steps.get-tag.outputs.tag_name }}" \
            --repo Aktesuixin/v2rayN \
            --title "${{ steps.get-tag.outputs.tag_name }}" \
            --notes "Automatically synced from 2dust/v2rayN" \
            *.zip *.tar.gz *.deb *.AppImage *.dmg  # 根据实际情况调整文件类型
