name: Watch Upstream Changes

on:
  schedule:
    - cron: "* 1 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Get Default Branch
        id: branch
        run: |
          # 动态获取当前仓库的默认分支
          default_branch=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Aktesuixin/v2rayN" | jq -r '.default_branch')
          echo "DEFAULT_BRANCH=$default_branch" >> $GITHUB_OUTPUT
          echo "Using branch: $default_branch"

      - name: Check Source Updates
        id: check-code
        run: |
          upstream_commit=$(curl -s \
            "https://api.github.com/repos/2dust/v2rayN/commits/${{ steps.branch.outputs.DEFAULT_BRANCH }}" | jq -r '.sha')
          fork_commit=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Aktesuixin/v2rayN/commits/${{ steps.branch.outputs.DEFAULT_BRANCH }}" | jq -r '.sha')
          
          if [ "$upstream_commit" != "$fork_commit" ]; then
            echo "CODE_UPDATE=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Code Sync
        if: steps.check-code.outputs.CODE_UPDATE == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'sync-code.yml',
                ref: '${{ steps.branch.outputs.DEFAULT_BRANCH }}',  # 使用动态分支
                inputs: {
                  source_commit: '${{ steps.check-code.outputs.UPSTREAM_COMMIT }}'
                }
              })
            } catch (error) {
              core.error("Trigger failed: " + error.message)
              // 自动回退到 master 分支
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'sync-code.yml',
                ref: 'master'
              })
            }
